# Generated by Django 6.1.1 on 2026-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en curso', 'En curso'), ('hecho', 'Hecho')], default='pendiente', max_length=20)),
            ],
        ),
    ]
