# Generated by Django 6.1.1 on 2026-09-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='posicion_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='posicion_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
