# Generated by Django 6.0.3 on 2026-09-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='clave_acceso',
            field=models.CharField(default='usuario', max_length=15),
            preserve_default=False,
        ),
    ]
