# Generated by Django 6.0.3 on 2026-09-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_clave_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='clave_acceso',
        ),
    ]
