# Generated by Django 6.1.1 on 2026-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuarios_clave_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(max_length=14),
        ),
    ]
